"""
Convert tools/backfill_data.json -> worker/seed.sql for D1.

- users: registered=0 (hidden) by default; Denis pre-registered=1 so there's a
  visible profile to verify right after deploy. strict=1 for Denis.
- entries: source='backfill', one row per (uid, day).
- uid is the NUMERIC telegram id (strip the export's "user" prefix) so live bot
  updates (from.id) match backfilled rows.

Run: python3 tools/make_seed.py
"""
import json
import re

DATA = "tools/backfill_data.json"
OUT = "worker/seed.sql"
DENIS_UID = "8607657267"  # Denis's LIVE account (post account-reset) — pre-register + strict
# Denis reset his Telegram account; his backfill history is under the old (now
# deleted) id 419686805 but his live account posts from 8607657267. Remap so
# history attaches to the live account.
UID_REMAP = {"419686805": "8607657267"}

TRANSLIT = {
    'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e', 'ё': 'e',
    'ж': 'zh', 'з': 'z', 'и': 'i', 'й': 'y', 'к': 'k', 'л': 'l', 'м': 'm',
    'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r', 'с': 's', 'т': 't', 'у': 'u',
    'ф': 'f', 'х': 'kh', 'ц': 'ts', 'ч': 'ch', 'ш': 'sh', 'щ': 'shch',
    'ъ': '', 'ы': 'y', 'ь': '', 'э': 'e', 'ю': 'yu', 'я': 'ya',
}


def translit(s):
    out = []
    for ch in s.lower():
        if ch in TRANSLIT:
            out.append(TRANSLIT[ch])
        elif ch.isalnum():
            out.append(ch)
        elif ch in ' -_':
            out.append('-')
    return re.sub(r'-+', '-', ''.join(out)).strip('-') or 'user'


def first_name(name):
    toks = re.sub(r'[^\w\s]', ' ', str(name), flags=re.UNICODE).split()
    return toks[0] if toks else str(name)


def q(s):
    """SQL single-quote literal with escaping."""
    return "'" + str(s).replace("'", "''") + "'"


def num_uid(export_uid):
    uid = re.sub(r'^user', '', export_uid)
    return UID_REMAP.get(uid, uid)


def main():
    with open(DATA, encoding="utf-8") as f:
        people = json.load(f)

    # unique slugs
    slugmap, used = {}, set()
    for p in people:
        base = translit(first_name(p["name"]))
        slug, i = base, 2
        while slug in used:
            slug, i = f"{base}-{i}", i + 1
        used.add(slug)
        slugmap[p["uid"]] = slug

    # NOTE: no explicit BEGIN/COMMIT — `wrangler d1 execute --file` batches
    # statements atomically itself and rejects SQL transaction statements.
    lines = ["-- generated by tools/make_seed.py — DO NOT COMMIT (gitignored)"]

    # users
    for p in people:
        uid = num_uid(p["uid"])
        slug = slugmap[p["uid"]]
        fn = first_name(p["name"])
        registered = 1 if uid == DENIS_UID else 0
        strict = 1 if uid == DENIS_UID else 0
        lines.append(
            "INSERT OR REPLACE INTO users (uid, slug, first_name, full_name, registered, public, strict) "
            f"VALUES ({q(uid)}, {q(slug)}, {q(fn)}, {q(p['name'])}, {registered}, 1, {strict});"
        )

    # entries (multi-row batched)
    rows = []
    for p in people:
        uid = num_uid(p["uid"])
        for day, sec in p["series"]:
            rows.append(f"({q(uid)}, {q(day)}, {int(sec)}, 'backfill')")
    BATCH = 100
    for i in range(0, len(rows), BATCH):
        chunk = ",\n  ".join(rows[i:i + BATCH])
        lines.append(
            "INSERT OR REPLACE INTO entries (uid, day, seconds, source) VALUES\n  " + chunk + ";"
        )

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {OUT}: {len(people)} users, {len(rows)} entries.")
    print(f"Denis (uid={DENIS_UID}) pre-registered + strict. Others registered=0 (hidden until claim).")


if __name__ == "__main__":
    main()
